//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_AI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int OD_ID { get; set; }
        public string Food_Name { get; set; }
        public int Quantity { get; set; }
        public double Food_price { get; set; }
        public int Order_ID { get; set; }
        public int Menu_ID { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Order Order { get; set; }
    }
}
